### ISSUE TITLE
Compiling issue of libHalf.so

### ISSUE THREAD

**Issue by MichaelFYang** [fzi-forschungszentrum-informatik/vdb_mapping_ros#2]
/usr/bin/ld: CMakeFiles/mapping_tests.dir/mapping.cpp.o: undefined reference to symbol '_ZN4half5_eLutE'
/usr/bin/ld: /lib/x86_64-linux-gnu/libHalf.so.24: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by lucasw** [comment]
I ran into that issue building on Ubuntu 23.04, his may help: https://github.com/lucasw/vdb_mapping/tree/ubuntu_2304 (and if that looks like a good solution and can be backwards compatible I can make a PR)

**Comment by MGBla** [comment]
Hey Michael, hey Lucas,

your changes should already be merged into the main branch by your previous pull request and it should work by now. At least I tested it on a 20.04 and 22.04 system. Did you pull the latest Version of the core library?

**Comment by MGBla** [comment]
Oh and thinking about it, which OpenVDB Version is currently installed on your system? I haven't run it with the apt version on 20.04 for a long time and it might be necessary to install a newer version.

**Comment by MichaelFYang** [comment]
Yes, It is the apt version vdb (I think it's 6.2) that actually fails. I upgraded it to 9.1.0 through the official website and now it works. But to make the 9.1.0 version work on ubuntu 20.04. I also need to upgrade the BOOST to 1.73.0

**Comment by MGBla** [comment]
Okay good to know, I always used the 9.0 version on my 20.04 and didn't had any further problems with boost or anything else (Currently i have 1.71 on my system). However not sure yet if and how to keep the compatibility to older VDB versions.

**Comment by lucasw** [comment]
I have `libopenvdb-dev 10.0.1-1ubuntu1` on 23.04

**Comment by MGBla** [comment]
Fixed in https://github.com/fzi-forschungszentrum-informatik/vdb_mapping/pull/6
